name: saat_bara_utara
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  equatable: ^2.0.5
  fpdart: ^1.1.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true



  assets:
    - assets/env/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserratFonts/static/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserratFonts/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserratFonts/static/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserratFonts/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserratFonts/static/Montserrat-Thin.ttf
          weight: 300
